/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2023.1.1.200.1
    Soft IP Version: 1.8.0
    2023 12 01 15:13:33
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module pll_ip (clki_i, clkop_o, clkos_o, clkos2_o, clkos3_o, clkos4_o,
    clkos5_o, lock_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clki_i;
    output  clkop_o;
    output  clkos_o;
    output  clkos2_o;
    output  clkos3_o;
    output  clkos4_o;
    output  clkos5_o;
    output  lock_o;
endmodule