/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2023.2.0.38.1
    Soft IP Version: 1.8.0
    2024 03 13 15:56:06
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module pll_sim_ip (clki_i, clkop_o, clkos_o, clkos2_o, clkos5_o, lock_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clki_i;
    output  clkop_o;
    output  clkos_o;
    output  clkos2_o;
    output  clkos5_o;
    output  lock_o;
endmodule