#
# Authored by: Robert Metchev / Chips & Scripts (rmetchev@ieee.org)
#
# CERN Open Hardware Licence Version 2 - Permissive
#
# Copyright (C) 2024 Robert Metchev
#

all:
	@mkdir bin -p
	g++ --std=c++14 -O3 -o bin/header src/header.cpp

clean:
	rm -f bin/header
