#
# This file is a part of: https://github.com/brilliantlabsAR/frame-codebase
#
# Authored by: Robert Metchev / Raumzeit Technologies (robert@raumzeit.co)
#
# CERN Open Hardware Licence Version 2 - Permissive
#
# Copyright © 2024 Brilliant Labs Limited
#
.PHONY: all

all:
	radiant frame.rdf
