#
# Authored by: Robert Metchev / Raumzeit Technologies (robert@raumzeit.co)
#
# CERN Open Hardware Licence Version 2 - Permissive
#
# Copyright (C) 2024 Robert Metchev
#

TEST_PATH := $(realpath .)
TEST_TOP := spi_test

include $(realpath ../../common/include.mk)

